import { Header, Home, Portfolio } from "@/components";
import type { Metadata } from "next";
import "./global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Home />
        <Portfolio />
      </body>
    </html>
  );
}
